# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn clean test
     - name: curl
      uses: wei/curl@v1
      with:
        args: -X POST -F file=@@target/surefire-reports/TEST-com.activeai.cucu_mvn.TestRunner.xml https://studio.cucumber.io/import_test_reports/21393011997680689515649256473428367644489147497337436841/527964/junit
